name       : libmspack
version    : '0.8'
release    : 9
source     :
    - https://github.com/kyz/libmspack/archive/v0.8alpha.tar.gz : 5c0aeec8f1b936dff9133f04e21ee357acfca9e0e045f84287f60ee3338f915e
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library for Microsoft compression formats
description: |
    libmspack is a portable library for some loosely related Microsoft compression formats
setup      : |
    cd libmspack
    %autogen --disable-static
build      : |
    cd libmspack
    %make -j1
install    : |
    cd libmspack
    %make_install
