name       : libmspack
version    : 0.5
release    : 3
source     :
    - http://www.cabextract.org.uk/libmspack/libmspack-0.5alpha.tar.gz : 8967f275525f5067b364cee43b73e44d0433668c39f9376dfff19f653d1c8110
license    : LGPL-2.0
component  : programming.library
summary    : A library for Microsoft compression formats
description: |
    libmspack is a portable library for some loosely related Microsoft compression formats
setup      : |
    %patch -p2 < $pkgfiles/security/cve-2017-6419.patch
    %patch -p2 < $pkgfiles/security/cve-2017-11423.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
