name       : libmspack
version    : 0.7.1
release    : 5
source     :
    - https://www.cabextract.org.uk/libmspack/libmspack-0.7.1alpha.tar.gz : 97a970db5093e34d4f50cb8daac1feebdf14acba912144417bd3aa323fdfc47e
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library for Microsoft compression formats
description: |
    libmspack is a portable library for some loosely related Microsoft compression formats
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
