name       : libmspack
version    : '0.8'
release    : 7
source     :
    - https://www.cabextract.org.uk/libmspack/libmspack-0.8alpha.tar.gz : 0533792e9561375a5fce1bc96bbc65ec778af486e0daa3803b226da9244addaf
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library for Microsoft compression formats
description: |
    libmspack is a portable library for some loosely related Microsoft compression formats
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install
